version: "3.0"
services:
  webapp:
    image: seoradar/webapp
    build:
      context: .
    env_file:
      - shared.env
      - private.env
    ports:
      - 3000:3000
    volumes:
      - ./:/opt/app
